name: Sabbath
options:
  bundleIdPrefix: com.sabbath
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  Sabbath:
    type: application
    platform: iOS
    sources:
      - Sabbath
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalsabbath.app
        INFOPLIST_FILE: Sabbath/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sabbath.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_CFBundleDisplayName: Sabbath
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
    attributes:
      SystemCapabilities:
        com.apple.FamilyControls:
          enabled: 1
        com.apple.ApplicationGroups.iOS:
          enabled: 1
    dependencies:
      - target: SabbathMonitor

  SabbathMonitor:
    type: app-extension
    platform: iOS
    sources:
      - SabbathMonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalsabbath.app.SabbathMonitor
        INFOPLIST_FILE: SabbathMonitor/Info.plist
        CODE_SIGN_ENTITLEMENTS: SabbathMonitor/SabbathMonitor.entitlements
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
    attributes:
      SystemCapabilities:
        com.apple.FamilyControls:
          enabled: 1
        com.apple.ApplicationGroups.iOS:
          enabled: 1

schemes:
  Sabbath:
    build:
      targets:
        Sabbath: all
        SabbathMonitor: all
    run:
      config: Debug
      executable: Sabbath
    profile:
      config: Release
      executable: Sabbath
    archive:
      config: Release
